### ISSUE TITLE
unknown M17 packet

### ISSUE THREAD

**Issue by DC9VQ** [n7tae/2urfd#1]
I installed your reflector with a local transcoder (2*Ambe3000 sticks). DCS, NXDN, YSF works but I get following error message when I transmit via M17. Link to ref was successful.

ep 22 11:02:56 debian urfd[1343]: Unknown M17 packet from xxxxxxx:
Sep 22 11:02:56 debian urfd[1343]: 0000:  4D 31 37 20 48 23 06 19 03 E5 3A ED 17 D7 86 AE    *M17 H#....:.....*
Sep 22 11:02:56 debian urfd[1343]: 0010:  6D 7C 00 05 00 00 00 00 00 00 00 00 00 00 00 00    *m|..............*
Sep 22 11:02:56 debian urfd[1343]: 0020:  00 00 00 0F CD 81 67 0E DC A6 61 28 CD 01 23 3A    *......g...a(..#:*
Sep 22 11:02:56 debian urfd[1343]: 0030:  16 FC 3F 68 00 00                                  *..?h..*

**Comment by DC9VQ** [comment]
one additional information receiving in M17 works

**Comment by n7tae** [comment]
This is the 16th packet and has a source callsign of `DC9VQ   D` and a destination callsign `M17-169 A`.  It's being rejected because of the "M17-" in the destination address. What client sent this packet?

**Comment by DC9VQ** [comment]
I use droidstar and tried tx successfully with another mref reflector e.g. M17-DEU. I registered my urf169 as m17 reflector in the registry instead of an urfd. Could that cause the issue ?

**Comment by n7tae** [comment]
Yes. The M17 mrefd registry is for mrefd reflectors only. By registering your urfd reflector there, any client that uses the mrefd registry will set the destination callsign with "M17-" and when that client tries to stream to the reflector, it will be rejected by urfd.

**Comment by DC9VQ** [comment]
Good to know. I seems that the urfd registration is still in development. Many thanks for your quick response.
73 from Germany
