### ISSUE TITLE
RX NXDN with Hotspot doesn't work

### ISSUE THREAD

**Issue by DC9VQ** [n7tae/2urfd#2]
Hi Tom,

I have following issue. NXDN connect to 2URFD works. 

I can send with a NXDN radio via a MMDVM Hotspot (WPSD) to the reflector but I can't rx via the hotspot. MMDVM stays in IDLE when someone sends on the 2urfd. Seems to be a network Issue. 

When I Use BLueDV with NXDN RX/TX works. When I use another NXDN Reflector with my radio and hotspot all works as expected (RX/TX). There is no special message in the log. Any ideas ? How can  I provide you some more details for a detailed analysis, any idea  ?

Okt 11 16:23:39 debian urfd[14169]: NXDN connect packet from DC9VQ    at 79.213.250.124:55085
Okt 11 16:23:39 debian urfd[14169]: New client DC9VQ    at 79.213.250.124:55085 added with protocol NXDN on module A
Okt 11 16:23:46 debian urfd[14169]: YSF server status enquiry from 79.213.250.124:55489
Okt 11 16:23:56 debian urfd[14169]: Opening stream on module A for client DC9VQ    with sid 0x2f04 by user DC9VQ
Okt 11 16:24:01 debian urfd[14169]: Closing stream of module A
Okt 11 16:24:01 debian urfd[14169]: TC round-trip time(ms): 22.9/39.2/58.2, 204 total packets
Okt 11 16:24:06 debian urfd[14169]: YSF server status enquiry from 79.213.250.124:55489
Okt 11 16:24:09 debian urfd[14169]: Opening stream on module A for client DC9VQ    with sid 0x9ad1 by user DC9VQ
Okt 11 16:24:14 debian urfd[14169]: Closing stream of module A
Okt 11 16:24:14 debian urfd[14169]: TC round-trip time(ms): 24.4/45.8/96.0, 172 total packets
Okt 11 16:24:16 debian urfd[14169]: Opening stream on module A for client DC9VQ    with sid 0xcd29 by user DC9VQ
Okt 11 16:24:22 debian urfd[14169]: Closing stream of module A
Okt 11 16:24:22 debian urfd[14169]: TC round-trip time(ms): 24.0/45.1/89.5, 212 total packets

73, Michael DC9VQ

**Comment by n7tae** [comment]
Sorry your having trouble, can you please check it the urfd/tcd predecessor is working? 2urfd and urfd have identical NXDNClient and NXDNProtocol source files. The latest is at nostar's git, https://github.com/nostar.

You can check if packets are going to nxdn clients by modifying CNXDNProtocol::HandleQueue(). Add two lines after the `Send(buffer. client->GetIp())`:

```
	Send(buffer, client->GetIp());
	std::cout << "Sent to " << client->GetCallsign() << " @ " << client->GetIp() << std::endl;
	buffer.Dump("NXDN Packet");
```

This is going to dump ever packet sent to each NDXN client, so only have one NXDN client and only do a short test transmission from another client. Hopefully there will be something obvious in the packet dumps.

**Comment by DC9VQ** [comment]
thanks Tom. Modified the source protocol file according to your proposal

Those packages are sent via BlueDV NXDN but not received by Hotspot/nxdn radio

NXDN Packet:
0000:  4E 58 44 4E 44 13 2D 30 39 01 AC 01 40 00 26 6E    *NXDND.-09...@.&n*
0010:  08 EF 41 50 EF F4 84 E4 21 D3 89 80 00 4D 07 C1    *..AP....!....M..*
0020:  40 47 1C 74 00 DD C6 D2 22 80 00                   *@G.t...."..*
Sent to DC9VQ    @ 79.213.250.124:14050
NXDN Packet:
0000:  4E 58 44 4E 44 13 2D 30 39 01 AC C1 01 00 2E 08    *NXDND.-09.......*
0010:  00 20 13 2D 66 9D 00 00 00 00 00 00 00 08 00 20    *. .-f.......... *
0020:  13 2D 66 9D 00 00 00 00 00 00 00                   *.-f........*
Closing stream of module A
TC round-trip time(ms): 24.5/41.8/77.8, 36 total packets


Those are sent by hotspot/nxdn radio and received by BlueDV

NXDN Packet:
0000:  4E 58 44 4E 44 13 2D 30 39 01 AC 41 D3 03 9A FF    *NXDND.-09..A....*
0010:  32 D2 D2 D2 D8 0A 78 A1 00 80 B8 C0 20 18 0E F4    *2.....x..... ...*
0020:  00 81 90 F4 01 5C A7 D0 E1 E0 00                   *.....\.....*
Sent to DC9VQ    @ 79.213.250.124:50169
NXDN Packet:
0000:  4E 58 44 4E 44 13 2D 30 39 01 AC 01 40 00 26 08    *NXDND.-09...@.&.*
0010:  00 20 13 2D 66 9D 00 00 00 D4 A0 00 00 08 00 20    *. .-f.......... *
0020:  13 2D 66 9D 00 00 00 D4 A0 00 00                   *.-f........*
Closing stream of module A
TC round-trip time(ms): 24.8/39.4/55.1, 48 total packets

**Comment by n7tae** [comment]
This suggests that packets are successfully being relayed by 2urfd. Without knowing why the hotspot is rejecting the packets from other clients, this is going to be very hard to troubleshoot.

I don't understand the scope of the problem. You said an MMDVM NXDN client will not hear a BlueDV NXDN client, but a BlueDV NXDN client will hear a MMDVM NXDN client. If two MMDVM NXDN clients are connected, will they hear each other? 

In your original issue, you said: "When I use another NXDN Reflector with my radio and hotspot all works as expected". What other Reflector were you using?

And did you try using urfd/tcd from nostar?

**Comment by DC9VQ** [comment]
>  You said an MMDVM NXDN client will not hear a BlueDV NXDN client, but a BlueDV NXDN client will hear a MMDVM NXDN client. If two MMDVM NXDN clients are connected, will they hear each other? 

 No they don't

When a NXDN User (BLueDV or MMDVM) sent via the reflector I can't hear it with a MMDVM NXDN (modem stays in idle) but I can hear it with BlueDV NXDN. When I change to an NXDN only reflector e.g.  20421 it works in all directions and all devices.

**Comment by DC9VQ** [comment]
I found the issue. I haven't open the firewall for IP6 traffic and it seems that was the problem :-)
Many thanks Tom for your quick support !!!!
